### ISSUE TITLE
several abstracts/localisation

### ISSUE THREAD

**Issue by darked89** [kks32/PhDThesisLyX#1]
I need to have three separate abstracts in three languages. What is a way to get this, with customized names for these abstracts? 
Many thanks for your help. It is really well designed, pretty template. 

Darek

**Comment by kks32** [comment]
Hi @darked89 

You need to edit the abstract section in https://github.com/kks32/PhDThesisLyX/blob/master/PhDThesisLyX.layout#L70. Have a look at the `babel` package for support for different languages.

**Comment by darked89** [comment]
Bit late but hopefully still relevant for others:
I ended up with simply adding ERT code inside of Lyx doc to include abstracts

```
%abstract eng
\selectlanguage{english}
\input{head/abstract_en}
%abstract es
\inputencoding{latin1}
\selectlanguage{spanish}
\input{head/abstract_es}
```

And the example abstract file:

```
\newenvironment{abstracten}%
{\cleardoublepage\thispagestyle{empty}\null\vfill\begin{center}%
\bfseries\abstractname\end{center}}%
{\vfill\null}
    \begin{abstracten}{english}
    Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
    \end{abstracten}
```

There is an easier way (i.e. normalize encoding for Lyx doc plus all the tex files => utf8), but above solution works. Also since 300 words abstracts are simple text only, Lyx superpowers are not needed to format them.

Best,

Darek Kedra

**Comment by kks32** [comment]
Great! Thanks!
