### ISSUE TITLE
List of figures/tables: number+figure+figure_name overcrowding

### ISSUE THREAD

**Issue by darked89** [kks32/PhDThesisLyX#2]
Hello,

I have perfectly looking TOC for chapters and roman pages. But the List of figures plus List of Tables are mangled: I got figure_number followed by word : figure (or rather figura, since the thesis main language is Spanish). The later one is being obscured by the figure_name. It makes these two parts unreadable. 
Best solution: no figura/figure or table in the list
Acceptable: fig 1.2 Title of fig 1.2

All three (Table of contents, List of figures and List of Tables) are Lyx commands with TOC being the first.

Thanks a lot for your help

Darek Kedra

**Comment by kks32** [comment]
Could you upload a snapshot? Are you using packages like `babel`?

**Comment by darked89** [comment]
Thank you for such a prompt answer. Yes, I got Babel. The text produced for first LOT entry (copied from PDF):
4.1table
Dos concepciones del pensamiento . . . . . . . . . . . . . . . . . . . . . . . 61

Word Dos overlaps with table. 
My feeling was that this may be something external (like updated version of texlive 2015 packages: the error producing box has the latest updates). No real emergency, but if it something obvious it will be good to fix it. I will test more older versions of my Lyx doc (+PhDThesisLyX.cls). And get some minimal trouble making examples.

Best,

Darek Kedra

**Comment by darked89** [comment]
Well, it did fix "itself" after today's upgrade of texlive packages.
